version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    volumes:
    - postgres_data:/var/lib/postgresql/data/
    env_file:
    - .env
    ports:
    - "${POSTGRES_PORT}:5432"
    networks:
    - postgres

volumes:
    postgres_data:
 
networks:
  postgres:
    driver: bridge
